export const rbv = `$$$$$$$$V*****:*:::::::::::****::****VVV*:****:::**::::***V$$VFV$$$$$$$$$$$$$$$$$$$$
$$$$$VV*:***::***::***IVIIVVVFI*IVIFVV*::****::*****::::*VVVFV$IV$$$$$$$$$$$$$$$$$$$
$$$$$VI*II***IF*I***VVV$V$$$$VFVV$VV**:**::*VV*IVV$$$***VV*:::*$VFV$$$$$$$$$$$$$$$$$
$$$$VI*IIIIIVI**IIIVV$$$$$$$$$$$$V*::***IVV$$$VV$$$VVFI*II*:**IV$VIIV$$$$$$$$$$$$$$$
$$$VFFVVVVVVFFVVVVV$$$$$$$$$$$$$VIIVVV$$$V$$$VVV$$VIIVVVV**::*V$*IVF*V$$$$$$$$$$$$$$
$VVVVVVV$$$$VV$$$$$$$$$$$$$$$VVVV$$$$VVVVVVVVIFFVV*VV$$$I**:**V$VF$V**I$$$$$$$$$$$$$
$$VIVV$$$$$VVV$$$$$$$$$$$$$$VVV$$$$$$$$$$$VI**FV$$$$$$VF***FVIV$$$$VVF*I$$$$$$$$$$$$
$VI*V$$$$VVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$VVVV$$$$$$$$$VIIIV$$V$$$$$$$VVI*$$$$$$$$$$$
$$VFVV$$$$$$$$$$$$$$$$$$VVVV$$$$$$$$$$$$$$$$$$$$$$$$$$V$$$$$$$$$$MMMM$$VIF$$$$$$$$$$
$$$VVV$$$$$$$$$$$$$$$VVVVVVVVVVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$M$$$$V$$$$$$$$$$
$$$$$$$$$$$$$$$VV$V$VVVVVVVVVFFFFVVVVVV$$$$$$$$$$$$$$$$$$MM$$$$$M$$$$$$MMV$$$$$$$$$$
VVV$$$$$$$$$$$VVV$$VVVII*********IIIIIIFVV$$$$$$$$$$$$$$$MMMMMM$$$MMMMMMM$$$$$$$$$$$
VVV$$$$$$$$$$$VV$$VFFI*************I*IIIFFVV$$$$$$$$$V$$$$$$MM$$$$$$MMMMM$$$$$$$$$$$
VVV$$$$$$$$$$$VVVVI********************IIIFVVVVVVVVVVVV$$$$$$$$$$$$$$MMM$$$$$$$$$$$$
VVVV$$$$$$$$$VV*II*:*******************IIIFFVVVVVVVVVVVVV$$$$$$$$$$$$MMM$VVVV$$$$$$$
VVVV$$$$$VFFF****::::*****************IIIFFVVVVVVVVVVVVVVVV$$$$$$$$M$$M$$$VVVVVVVVVV
FVVVV$$$$****************************IIFFVVVVVVVVVVVVVVVVVVVVV$$$$$$$MM$$$$$$V$VVVVV
IIIIIV$$$*******IFVVVFIII***********IIIIFFVVVVVVVVV$$$VVVVVVVV$$$$$$MM$$VVVVVV$VVVVV
****IV$$V**********IIII*****************IIFFIIFFFFFVVVVVVVFFVVV$M$$MMM$VVVVVVVVVVVVV
*****I$$V***::*****IIFFFII***********IIFFVFFIIIIIIIIIIIFVVFFFVV$$$$$$$$VVVVVVVVVVVVV
******V$V*******IVVVVVVVVVI*******IIVVVVVVVVVVVVVVVFFFIIIFFIFFV$$$$$$$$VIFFFFFFVVVVV
******F$V::*****I$$$$VIFVFI*:::**IVVVVVVVF*V$$$$VVVVVVVFIFFFFFV$$$$$$$VVFIIIFFIIIIFF
*******VV:::::***FVVVVFVFI*:..:**IVVVVVVVVIV$$$VIVVVVVVVFFIIIFV$$$$$$VFIIIIIIIFFFIII
********F:::::::****IIII**:...:**IFVVVVVVVVVVVVVVVVVVVVVVFFIIFV$$$$VVVVIIIIIIIIIIIII
*********::....::::****:::....::*IIFVVVVVVVFFFFFFVVVVVVVVFFFFFV$$VFFVVI********I*II*
*********:::.....::::.::......::**IIIIIFVVFFFFIIIIFFFFFFFFIFFVV$VVFFVV**************
*********::::.........:::.....::***II**III*IIIIIIIIIIIIIIIIIFVVVVVVVVF**************
*********::::.....:::::::...::::***III***********IIIIII**IIIFVVVVVVFV***************
*********:::::::::::::::::::::*******II*************IIIIIIIIVVVVFFVVI***************
**********:::::::::::**::*********I***II*****************IIIVVVVFVVI****************
**********:::::::::****::*II*****VVVIIFI*****************IIVVVVVVFF*****************
**********::::::::****::.:*******IFVVFII*****************IIVVVVFFI******************
:::::::****::::::****:::::::******IIIIIII***************IIVVF***********************
:::::::::**::::::****::::::::*****IIIIIIII**************IIVV************************
::::::::::**::::****************IIIII****I**************IFV*************************
:::::::::::**:::****IIII*****IIFVVVVVVVVVFII***********IIF**************************
:::::::::::FF*********:::::::***IIIFVVVVVVFI**********IIFVV*************************
:::::::::::F$V*******:::::*********IIIIIFFII*********IIFV$M$V***********************
:::::::::::*$$VI*****::****************IIIIII******IIIV$MMMM$I**********************
::::::::::::V$$$VF***:::***************IIIIIIIIIIIIIFV$MMMMM$V**********************
*********IVV$$$$$$VI*:::::::************IIIIIFFVVVVV$$MMMMM$$I**********************
**FV$$$$$$$$$$$$$VV$V**::::::***********IIIFVVVVVV$$MNMMMMM$$***********************`;

export const angi = `$VVVVV$$$VVV$$$VVVVVVV$$$VVVVFVIFVI******IFFFIIIFFFFFFFIIIIIIIIII************************************
$VVVVV$$$VVFV$VVVVFVVV$VVVVVFII**F**:*:::**********FVVVVV********************:::::::::::::::::::*****
$VVVVV$$$VVVVVVVVVFVVV$$VVVVF****FI***::::********V$$$$$$$I******************:::::::::::::::::::::***
$VVVVV$$$VVV$$VVVVFVVV$$VVVVF****FI***:::*****FFVV$$$$$$$$VIII*************::::::::::::::::::::::::**
VV$VVV$$$VVV$$$$$VVVVV$$VVVVF****FI****:****II*FV$$$$$$$$$V*I***********::::::::::::::::::::::::::::*
VVVVFV$$VVVV$$VVVVVVVV$VVVVVF****FI*****::***V$$$$$$$$$$$$$VI**********::::........................::
VVVVVV$$VVVV$VVVVVFVVV$VVVVVF****II*****::**$$$$$$$$$$$$$$$$$V********::............................:
VVVVV$$$VVVV$VVVVVFVVV$$VVVVV****FI********$$$$$$$$$$$$$$$$$$$V********::...........................:
$$VVV$$$VVVV$$VVVVFVVV$$$VVVVI***FF******IV$$$$$$$$$$$$$$$$$$$$********:............................:
VVVVV$$$VVVV$VV$VVFVV$$VVVVVVI***FFI*****IV$$$$$VVVIIIFVV$$$$$V********:::........................:::
$$VVV$$$VVV$$VVVVVVVV$$VVVVVV****VVF***:*FIV$VVVVVVFIIVV$$$VVV************:::::::::::::::::::::::::**
$VVFV$$VVVV$$VVVVVVVV$$$$VVVF****VVFII*:*FVVVVVV$$$$V$$$$$VV$VI********************:::::*************
$VVFV$$VVVV$$VVVVVVVV$$$$VVVV****VVFIFI:*FFVVVFFVVFV**VVVVVVVVI**************************************
$VVFV$$VVVV$$$$VVVVVV$$$VVVVV****$VF*I*:*FFV$FIIIIV***VVVVVVVV***************************************
VVVFV$$VVVV$$VVVVVVVV$$$$VVVVI***VV*:**:*FVV$VVIIIFVVVVVFVVV$VI**************************************
VIIFV$VVVVV$$VVVVVV$V$$$$VV$VI**IVVF*II:*FFV$$VVFVVVV$$VVVV$$VFIIIIII********************************
VIIIV$VVVVV$VVVVVVV$V$$$$VVVVI*IIVVV*II**VFVV$$$VVVVVVVVVV$$VVVVVVVVVVVVVVVVVVVVVVVFFFFFFFFFVVVVVVVVV
VFIIV$VVVVV$VVVVVVVVV$$$$VVVVII**VVVVFI*IVVVV$$$$VVVVVVVV$$$V$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
VIIF$VVFFFVVVVVVVVVVV$$$$VVVVFI*IVVVVVVVV$$$$$$$M$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
VIIF$VFFFVVVVVVVVVVVV$$$VVVVVVVVV$V$$V$$$$$$$$$$$$$$$$$$$$$V$$$$$$$$$$$VVV$$$$$$$$$$$$$$$$$$$$$$$$$$$
VIIV$VFFVV$VVVVVVVVVV$$$VVVVVVVVV$$$$V$$$$$$$$$$$$$$$$$$$V$$$$$$$$$$$$$$$$V$$$$$$$$$$$$$$$$$$$$$$$$$$
VIIV$VFFVVVVVVVVFVVVVV$VVVVVVVVVV$$$$$$$$$VV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$VV$$VVVVVVVVVV$$$$$$$$$$$
VIIVVVIFVV$VVVVVVVVVVV$VVVVVVVVV$$$$$$$$$$VVV$$$$$$$$$$$$$$$$$$$$VV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
VFFVVVIFFVVVVVVVVVVVVVVVVVVVV$$$$$$$$$$$$VVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$VVVVVVVVVV$$$$$$$$$$$V
VIFVVFFVFVVVVVFVFVVVVFVVVVVVV$$$$$$$$$$$$VVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V::::*******VVVVFVVVI*
VIFVVVVVVVVVVVVVVVF******VV$$$$$$$$$$$$$$VVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V*::**:*************I
VFV$VVVVVVVVVVVVV**********V$$$$$$M$$$$$$VVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V**I****************
VFV$VVVVVVVVVVVI************V$$$MNM$$$$$$VVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F******************`;

export const somesh = `VVVIIII*************I*IIIIFFFVVVFF***********FVVFVVFVVVV*VVVVV$$$$$$VI*V$$$$$$$$$$$$MMMMMMMMMMMMMMMMMMMM$$$$$V****************************************
VVVVVVVVFIFVVVFIFVVVVVVVVVVVVVFIII***********IVVVV$$VVVV*VV*VIVV$$VVVFV$$$$$$$$$$$$$$MMMMMMMMMMMMMMMMMMMM$$$$$$VI***********************I*IIIIIIIIIFII
$$$$$$VVVVFFVVF*I$$$$VFFVVV*******************VVVV$VVFFI*VVIFIFVVVVVV$$$$$$$$$$$$$$$$M$$$$$$MMMMMMMMMMMMMMMM$$$$VI****IIIIFVV$$$VVVVVVVVVVVVVVVVV$VVVV
$$$$$$$$VVV$VVV**VVVVV**VV**::::::************VV$$VVVIFF*VFIFFIIVVVV$$$$$$$$$$$$$$$$$$$$$$$$$MMMMMMMMMMMMMMMMM$$$$VVVVVVVVV$$$$$$$$$$$$$VVVV$$$$$$$$$$
$V$$$$$$FV$$$V*FIFVVVVVVF***:::::*************VFVVVVVVVVVVVVVVVVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$MMMMMMMMMMMMMMM$$$$$$VVVVVVV$V$$$$$$$$$$$VVVV$$$$$$$$$$
$V$$$$$$$V$$VFIIFVV$V$VV**********************VVIIFVVVVVVVVVVIFVVV$$$$$$$$$$$MM$$$$$$$$$$$$$$$$MMMMMMMMMMMNMMM$$$$$$V*FVVVVVV$V$$$$$$$$$VVVV$$$$$$$$$$
$$$$$$$$$$$$$VVVVVVVV$$VFIFI******************VVVIV$$VV$$$$$$VVVV$$$$$$$$MMMMM$$$$$$$$$$$$$MMMMMMMMMMMMMMMMMMM$$$$$$$VVF$$VVVVV$$VVVV$$$VVVV$$$$$$$$$$
$$$$$$$$$$$$$$VVVVVVVVVVFFVVVVVFIII***********FV$VVVVVVVVVVVVVV$$$$$$$$MMMMMMMMMMMMMMM$$$$$$MMMMMMMMMMMMMMM$$$$$$MMM$VIIVVVVVVV$$VVVV$$$$$$$$$$$$$$$$V
$MMMMMMM$$$$$$$$$VVVVVVVIIVVVVVFIIIVI*IIIFIIIIFVVVVV:*FFVVVVVVVV$$$$MMMMMMMMMMMMMMMMMMM$$$$M$$$MMMMMMMMM$$$$$$$$$MMMM$VFFVVVVVV$$VVV$$$$VVFI*******I**
$MMMM$$$$$$$$$$$$$$$VVVVI*IVVVFFVVVVVVVFFVVVVVFV$VFF**IFVVVVVVVV$$$MMMMMMMMMMMMMMM$$$$$$$$$$$$$$$$$$$$$$$MMMMMMMMMMMMVIIIIVVVVV$$VFFVI**:::::::::::**I
$$$$$$$$V$$$$$$$$V$$$V$$IIIIIIFVI***VVVVVVVVVVIV*III***IFIFVVVVV$$$MMMMMMMMMM$$$$$VVVV$$$$$$$$$$$VVVVVV$$MMMMMMMMMMM$VIFVVVVVVV$VF**************I*V$$$
$V$$V$$VF****I$$VV$$$V$VII**IIIFI*IIIFVVVVV$$V*I*III**IIIIIVVVVV$$MMMMMMMMM$$VVFFFIIIIIFVV$$$$$VVVVVVVVVV$$MMMMMMMMM$VV$VVV$$$$F*************::*$MM$$$
VIV$$$$$V$$$V*VVVVV$$$$VVV**I*IVF*********IV$$******IIIIFFFFIFVV$MMMMMMMMM$VI*************IVVVVIIIIIIFFFVV$$MMMMMMMM$VV$VVVVF**::::::::::::::::*V$$F**
VV$$$$$VV$$$$VVVV$$$$$$$VFI****FIII*******I$$$F****IVFIIIFIIIII*F$MMMMMMM$VI*************************IIIIFVV$NNMMMMMVVVVI*:::::::::::::::::::**VVV$VI*
VVVV*V$VVVVV$$VVV$$$$$$VI*I*:::******IFVVFV$$$VVVVVVVVVFFFFIIIIIV$MMMMM$$V*******************************IIVV$MMMMM$VVVF::::::::::::*:::***:*$V$$VVVVV
$$$$$$$$$$$V$VVVVV$$$VVVVVVV****FI****VVVFVV$$VIIVVVVVVVVFVVFVVVFIV$MM$V******IFFVVVVVFFII*****IIFFVVVVVVVVVVV$MMM$$$$V*:::::::::::::::::::*V$MMMMM$$$
$$$$$$$$VVVVVVVVFFVVVVVVVVVVVVVVVVVVVFIFVVVV$$$VVVVVVVVVVVVVIFVVVVVV$M$I***IFVVVVV$$$$$$VVFIIIFVV$$$$$$VVVVVVV$M$$VVVVV********************V$M$$$M$$$V
$$$$$$$$FVVVVVVVVVV$VV$$$$$$$$$V$$VFVVI**FV$$$$VVVVVVVVVVVVVVVVVVV$VV$$I*IFVVV$$$$$$$$$$$VFIIIVV$$$$$$$$$$VVVVV$$$VVVVFFVVFFFVVVVV$V*******$$$MMMMMM$I
$$$$$$$$$VVF*FVVVVV$$$$$$$$$$$$$$$$VVVII**V$$$$IIVVVVVVVVVVVVVVV$$VVV$$I*IIVVVVVVVV$$VVVVVI***VVVVVIV$$$$$VVVVV$VV$MMMM$$$$$$$$$$$$V*****IF$$MMMMMM$V*
$$$$$$VVV$$VVVVVVV$$$$$$$$$$$$$$$$VIII*I*IV$$$$VVVVVVVVVVVVVVV$V$$$VVVVF******IFVVVVVFIIII****FVFFFVVVVVVFIIFVV$V$$$$MMM$$$$$$$$$$$VVV$$$$$$$$$MMMM$VI
$$$$$VV$VV$$VVFFVVV$$$$$$$$$$M$$$$V**V*F**V$$$$$VVVV$$$$VVVV$VVV$$$V*IVVI*********************III*****I***IIFVVVV$$V$MMM$$$$$$$$$$$VVVV$VVVVV$$$$$VV$$
$M$$$VVVIV$$VFFVVV$$$$V$$$$$$$$$$VVVFVVVV**V$$$$VVV$V$$$VVVV$$$$$$$$V*VVI**********************II**********IFVVV$$$$$$MMMMM$$$$$$$VVV$$$F*IV$$$VI****V
$$$$$VVVVV$VVV$$$VV$$$$$$$$$$$$$$VVIIV$$$VIVV$$$VV$$V$$VVVVVV$$$$$$$$I*FI*************I********III*********IFVV$$$$$$$MMMM$$$$$$$$V$$$$$$VFF$$V**VVFFV
$$M$VVVVVVV$$VVV$$$$$$$$$$$$$$$$$$VVVV$VVVVVVV$$VVVVVV$$VVVVV$$$$$$$$VVVII*******IIFFI********II*II*******IIVV$$$$$$$$MMMMM$$$$$$$$VVVF$M$VVVV***VI**V
$$$$$$$$V$$$$$$$$V$$VV$$$$$$$$$$$$VVV$VVVVFFVV$$$VVVV$$VVVVVVV$$$$$$$$$VVFIIIIIFVVVVI*FVV$VVVVVVVF**IIIIIIIFVV$$$$$$$$$$MM$$V$$$$$$I*FV$$$$$$VI**F****
$$$$$$$$VV$$$$$VVV$$$V$$$$$$$$$VVVVVFVVIVVFVVVV$VVVVV$$VVVVVVVVV$VV$$$$$VFFFFVVVVVVFIIIVVV$$$$$VVIIIFFIIFFFVVV$$$$$$$$MMM$$VVV$$$$VVFV$$VV$$$$V**V****
*V$MM$$$$VV$$$VVVV$VVVVVV$$$VVI***IVVVVVVVVVVVVV$VVVV$VVVVVV$V$$VV$$$$$$VVVVVVFVV$$VVFIIIFVVVVFFFFVVVVFFIVVVV$$$$M$$MM$$$VV$$$$$$$VVV$M$$$$$$$V**VI***
**$MMM$$$VV$$$$VVVVVV$$VVV$VI******IVV$$$$$VVVV$$VVVV$$V$$$$$$$VVVVV$$$$VVVVVVVFFVFVVVVVVVVVVVVVVVVVVVFFFVVVV$$V$$$$$M$$VV$$$$$$$$$FV$M$$$M$$VV**II***
*$MM$$$$$VV$$$VVVVVVVV$VVVVV****IIIFVV$$$$$$$$VVVVV$VV$$$$$$$$$$$$$$$$$$$$VVVVVVVIIIIFFII****IIFVVFIFVVVVVVV$$$V$MM$MMM$$$$$V$$$$$$FV$$M$VVVFI***VF***
*I$$$M$$$VVV$VVVVFFFIFVVFVVVF***VVVVVVVVVVVVVVVVVVVVVV$VV$$$$$VV$$$$$$$$VVVVVVVVVFI**IFVVVVVVVVVVIIIFVVVVVFF$$$$$MMMMMM$$$V$V$$$$$$FV$$M$VVVFVVFVV$VVV
V$$VVVVVVFIFVVVVVVVVVVVVVVVVVI*IVVVVVV$$$$$$$$$$$$VVV$$$$$$$$$V$$V$$$$V$$V*V$FVVVVIII**IIIVFFFIIIIIFVVVVVV**V$$$$MMM$$$$$$$$$$$$$$$V$$MM$FIII*I**VVIIV
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVFIIFFIV$$$VVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*:*VVFVVVVFIIIIIIIIIIIIIFVVVVVVVI***$$$MMMMM$$$$$$$$$$$$$$V$$MM$FF$VFIIIFFIIF
VVVVVVVVVVVVVVVVVVVVFFVVVVVVVFIFFFFFV$VVVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*:**VVFVVVVVVVVVVVVVVVVVVVVVV$VF*****IVV$$$M$$$$$$$$$$$$$$V$$M$$IIVVFFFFVVFII
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVFFFFVVFVVVVVVVVVVVVVVVV$$VVF*V$$$$$$$$$$$$$V:::**VVFVVVVVVVVVVVVVVVVV$$$$VI***********VV$$$$$$$$$$$$$$$$$$$VFFVVFIIFV$VII
VVVVVVVVVVVVVVVVFVVVVFVVVVVVVFFFFIIFVVVVVVVVVVVVVV***::::*$$$$$$$$$$$$$$F::::**IVVVVVVV$$$$$$$$$$$$$VI******************FV$$$$$$$$$$$$$$VFFVVFIFF$$VFI
VVVVVVVVVVVVVVVVFVVVVFVVVVVVVVIFFFFFVVVVVVVVVVV**:::::::*V$$$$$$$$$$$$$$*::::::**V$VVV$$$$$$$$$$$$VI************************V$$$$$$VVVVVVFIFFIIIIFVIVI
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVFVVFFFVVVVVVVVVV*:::::::::I$$$$$$$$$$$$$$V::::::::**VV$$$$$$$$$$$VVF****************************IV$$$VVVVVVFIFFIIIIII*FI
VVVVVVVVVVVVVVVVVVVFIVVFF*IFVVVFFFVVV$VVVVVVVF:::::::::*V$$$$$$$$$$$$$V*:::::**V$M$VFVVV$$$VIVVF********************::::::*******IVVVVVVVFIIIIIII***II
VVVVVVVVVVFII****IIIIVFIIIVVVVVVVVVVVVVVVV$$V::::::::::F$$$$$$$$$$$$$V*:::*FVVVVV$$$$$$$$$M$V*********************:::::::::::::******VVVVVFFFFVFFIIII*
VVVFFFI******I**IFVVVVVVVVVVVVVVVVVVVVVVVV$$F:::::::::*V$$$$$$$$$$$$$*:::**I******V$$$$$$$$$$$************:******::::::::::::::::::****FV$VVVVVVI*****
FIII*IIIIFVVVVVVVVVVVVVV$$$VVVVVVVVVVVVVVVVV*::::::**:*$$$$$$$$$$$$$V::::**********IV$$$$$$$$$$I***:::::::*****::::::::::::::::::::::****VVVVVVI******
VVVVVVVVVVVVVVVVVVV$$$$VV$VVVVVVVVVVVVVVVVVI**:::::****$$$$$$$$$$$$$*:::**::**:*****F$$$$$$$F**FI*::::::::******:::::::::::::::::::::::****FVVV*******
VVVVVVVVFFVVVFFVVVV$$$$VVVVVVVVVVVVVVVVVVVV*:**::*:****$$$$$$$$$$$$F::**::::::::****V$$$$$V*********:::::*******::::::::::::::::::::::::*****VV*******
VVVVVVVVFIFFFFVVVVVV$$$$$$VVVVVVVVVVVVVVVVV*:**********$$$$$$$$$$$$*:::::::::::::*:*$V$$$$V************::****::::::::::::::::::::::::::::*****II******
VVVVVVVVFVVFVVVVVVVVV$$$$$V$$$$VVVVVVVVVVVV*********:**$$$$$$$$$$$V::::::::::::::::FVV$$$$$I**********I*****:::::::::::::::::::::::::**::*************
VVVVVVVVVVVVVVVVVVVV$VV$$$$VVV$VVVVVVVVVVVI:***********V$$$$$$$$$$*:::::::::::::::*VV$$$$$$$*****::::*****::::::::::::::*::::::::::*********::********
VVVVVVVVVVVVVVVVVVVVVVV$$$$$$$$V$VVVVVV$$$I:***********V$$$$$$$$$V::::::::::::::::*VV$$$$$$$V**::::::::::::::::::::::::::::::::::::***************IFVV
VVVVVVVVFVVVVVVVVVVVV$$$$$$$$$$$VVVVVVV$$$*:*:*********V$$$$$$$$$*::::::::::::::::IVV$$$$$$$V**:::::::::::::::::::::::::::::::::::****************FV$$
VVVVVVVVVVVVVVVVVV$$V$$$$$$$$$$$$$$$VVV$$$*************V$$$$$$$$V:::::::::::::::::VV$$$$$$$$$**:::::::::::::::::::::::::::::::::******************V$$$
VVVVVVVVVVVVVVVV$$$$$$$$$$$$$$$$$$$$VVV$$V*************V$$$$$$$V*::::::::::::::::*VV$$$$$$$$$I*:::::::::::::::::::::::::::::**********************I$$$
VVVVVVVVVV$$$$$$$$$$$$$$$$$$$$$$$$VVVVVVVV*************V$$$$$$$*:::::::::::::::::*V$$$$$$$$$$V***:::::::::::::::::::::::***************************V$$
VV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$VV$$$$$$V*************V$$$$$MV***:::::::::::::::*V$$$$$$$$$$V****:::::::::::::::::::******************************FVV
$$$$$$$$$$$$$$$$$$$V$$$$$$$$$$$$$$$$$$$$$V*************V$$$$M$**:::::::::::::::::*$$$$$$$$$$$$****:::::::::::::::::::*******************************VV
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V*************V$$$$$I:::::::::::::::::::*$$$$$$$$$$$$V***::::::***::::**:::********************************V$
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$VVVF**************I$$$$V*:::::::::::::*:::::*$$$$$$$$$$$$V****::::::***::**************************************I$
$$$$$$VV$$$$$$$$$$$$$$$$$$$$$$$$VVVVIIIII*************IF$$M$*::::::::::::::**::::*$$$$$$$$$$$$$******:::::::::***************************************V
$$$$$$$$$$$$$$$$$$$$$$$$$$VVVVIIIII*IIII**::***********I$$MV::::::::::*******::::*$$$$$$$$$$$$$I*********::::::**************************************F
$$$$$$$$$$$$$$$$$$$$VVVVFI*****************::**********F$MMV***:::::::*****:::::**$$$$$$$$$$$$$V****::**************************IIIVV*****************
$$$$$$V$$$$$$$$VVVFI***********************::::********$$$$*******::::::::::::::**$$$$$$$$$$$$$V****:**************************IFIVVV*****************
$$$$$$$$$VVVVFI*************************I*************F$$M$********:::::::::::::**$$$$$$$$$$$$$$*******************************IVVVVF*****************
$$$VVVFII**********************************:**********V$$M$***::*****::::::::::***V$$$$$$$$$$$$$F******************************IVVVVI*****************
FII******************************************::::*****IV$$V****::******::::::::::*V$$$$$$$$$$$$$V******************************IVVVFI****I************
******************************IIIIIIII******::::::*****I$******:::******::::::::**V$$$$$$$$$$$$$$******************************VVVVII***I*************
******************************IIIIIIIIIIII**:::::::::**$F:******::::*****::::::::*V$$$$$$$$$$$$$$F****IFVFFFF*****I***********FVVVVI**II**************
****************************III***IIIIII**:**::::*****$$*********::::*****:::::::*V$$$$$$$$$$$$$$V*******VVFIII***************IVVVIIIII***************
**************I**********I***IFVVVVVVVVF*::::*********$V*********:::::*****::::::*F$$$$$$$$$$$$$$$****I**$V********************VVFIIIII***************
************************IIIVV$$$$$$$$$$$$V*:*********VMF**********:::::****::::::*I$$$$$$$$$$$$$$$I******$$VFF*****************VVFIIFI****************
IIII****************IIIIIV$$$$$$$$$$$$$$$$$V*::::::**V$*:**********:::::****::::::I$$$$$$$$$$$$$$$V****IFVVF******************V$VFFVI*****************
FVVFII*******IIIII****IV$$$$$$$$$$$$$$$$$$$$$$VI*****V$*************:::::****:::::*$$$$$$$$$$$$$$$$I***********************:**$VVVVI******************
FI***IIIFFFI*********V$$$$$$$$$$$$$$$$$$$$$$$$$$$$V**V$I*************:::::***:::::*$$$$$$$$$$$$$$$$I**********************:.:**V$VI*******************
IIFVVVVVFIIIFII****IV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V*************::::::*:::::*$$$$$$$$$$$$$$$$V**********************::****VI********************
VVVVFFFFVVFI***IFVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$M$V********::****:::::::::***$$$$$$$$$$$$$$$$$********************::****************************
VVVFIIVVVVFFVVVVVV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V********:::****::::*::****V$$$$$$$$$$$$$$$$V*****************:::*********FFI***************::
IIFFVVVVVVVVFIFFV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V*********:::****:::::::::*V$$$$$$$$$$$$$$$$$FI**************::***********FVVVFII***::::::::::
VVVVVVVVVFFFFFIIV$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V**********::::**:::::::::*V$$$$$$$$$$$$$$$$$I**IFFI**********************VVI***********::::::`;
